management.endpoints.web.exposure.include: "*"

eureka:
  instance:
    hostname: localhost
    # registers with ip address instead of hostname
    preferIpAddress: false
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

# spring.zipkin.base-url: http://localhost:9411