PORT: 8861

eureka.client.registryFetchIntervalSeconds: 5

swagger.enable: true

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    movie-catalog-service:
      path: /movie-catalog/**
      serviceId: movie-catalog-service
      stripPrefix: true
    user-info-service:
      path: /user-info/**
      serviceId: user-info-service
      stripPrefix: true
    library-service:
      path: /library-api/**
      serviceId: library-service
      stripPrefix: true
    book-service:
      path: /book-api/**
      serviceId: book-service
      stripPrefix: true
    user-service:
      path: /user-api/**
      serviceId: user-service
      stripPrefix: true