server:
  port: 8082
  servlet.context-path: /book-api
  error.include-stacktrace: never

spring:
  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: none
    # hibernate.ddl-auto: create-drop
  datasource:
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    # persistent store
    # url: jdbc:h2:file:~/data/dump
    # volatile store
    url: jdbc:h2:mem:jpop

# DB Migration
spring.flyway.enabled: true
flyway:
  url: jdbc:h2:mem:jpop
  schemas: BOOKSERVICE
  user: admin
  password: admin
  locations: filesystem:db/migration

#actuator configs
management:
  endpoints:
    enabled-by-default: true
    web.exposue: health

#swagger configs
#configure the path for swagger ui html. Default is /swagger-ui.html
#configured to default context path
springdoc:
  show-actuator: true
  packagesToScan: in.hp.java.bookservice
  pathsToMatch: /books/**
  swagger-ui:
    enabled: true
    path: /
  api-docs:
    enabled: true
    path: /docs

#swagger ui properties
swagger-custom:
  name: Book API
  version: '@project.version@' #this will be coming from pom
  description: '@project.description@'
  contact:
    name: Hariprasath
    url: https://github.com/hariprasath-r